user: quake3
cmd: /opt/ioquake3/ioq3ded.x86_64
exec: /home/quake3/.q3a/baseq3/autoexec.cfg
gamemodes:
  # names just identifiers, feel free to mix
  # map types as you see fit
  default:
    # the only required option here is maps,
    # everything else is optional
    maps: [
      q3dm2, q3dm3, q3dm4, q3dm5, q3dm6,
      q3dm7, q3dm8, q3dm9, q3dm10, q3dm11
    ]
    # any supported var can be set from here
    # vars is optional, defaults to these:
    vars:
      fraglimit: 15
      timelimit: 5
  duel:
    maps: [
      q3dm1, q3dm2, pro-q3dm6, pro-q3dm13,
      q3tourney1, q3tourney3, q3tourney5, q3tourney6,
      pro-q3tourney2, pro-q3tourney4
    ]
    vars:
      fraglimit: 15
      timelimit: 5
  cpma_duel:
    maps: [ q3dm6 ]
    vars:
      # mods can be used as well
      fs_game: cpma
      fraglimit: 15
      timelimit: 15
# defining bots here is optional, defaults
# are already defined in the script
bot_level: 3
bot_names: [
  anarki, angel, crash, doom, hunter,
  klesk, major, mynx, orbb, slash, xaero
]
