user: quake3
cmd: /opt/ioquake3/ioq3ded.x86_64 +exec autoexec.cfg
autoexec: /home/quake3/.q3a/baseq3/autoexec.cfg
gamemodes:
  any:
    vars:
      fraglimit: 100
      timelimit: 10
  ffa:
    maps: [
      q3dm2, q3dm3, q3dm4, q3dm5, q3dm6,
      q3dm7, q3dm8, q3dm9, q3dm10, q3dm11
    ]
    vars:
      fraglimit: 30
      timelimit: 15
  duel:
    maps: [
      q3dm1, q3dm2, pro-q3dm6, pro-q3dm13,
      q3tourney1, q3tourney3, q3tourney5, q3tourney6,
      pro-q3tourney2, pro-q3tourney4
    ]
    vars:
      fraglimit: 15
      timelimit: 5
bots:
  level: '3'
  names: [
    anarki, angel, crash, doom, hunter,
    klesk, major, mynx, orbb, slash, xaero
  ]